\documentclass{article}

\usepackage{fullpage}
\usepackage[colorlinks=true]{hyperref}
\usepackage[tableposition=top]{caption}
\usepackage[utf8]{inputenc}

\begin{document}
\SweaveOpts{concordance=TRUE}

\title{Analysis of Body Weights for High Fat Diet and Particulate Treatment Study}
\author{Alyse Ragauskas, Matt Peloquin, Sridhar Jaligama, Jyothi Parvathareddy, Stephania Cormier and Dave Bridges}
\date{\today}
\maketitle

This study involved two arms, animals treated as neonatal pups and animals treated \textit{in utero}.  These data are located in \verb+\Sexpr{getwd()}+ and was most recently updated on \Sexpr{date()}.

<<data-entry, echo=FALSE>>=
 library(rjson)
 library(RCurl)
output_file_pups <- "Raw Weights - Pups.csv"
output_file_maternal <- "Raw Weights - Maternal.csv"

 #find out which  mice are high fat diet (all mice ever)
update.data <- function(x) {all.c57bl6.url.group1 <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/data/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=0&animal__strain__Strain__icontains=C57&animal__MouseID__isnull=False'
all.c57bl6.url.group2 <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/data/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=0&offset=1000&animal__strain__Strain__icontains=C57&animal__MouseID__isnull=False'
all.c57bl6.url.group3 <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/data/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=0&offset=2000&animal__strain__Strain__icontains=C57&animal__MouseID__isnull=False'
all.c57bl6.url.group4 <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/data/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=0&offset=3000&animal__strain__Strain__icontains=C57&animal__MouseID__isnull=False'
all.c57bl6.url.group5 <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/data/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=0&offset=4000&animal__strain__Strain__icontains=C57&animal__MouseID__isnull=False'
all.c57bl6.url.group6 <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/data/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=0&offset=5000&animal__strain__Strain__icontains=C57&animal__MouseID__isnull=False'
all.c57bl6.url.group7 <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/data/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=0&offset=6000&animal__strain__Strain__icontains=C57&animal__MouseID__isnull=False'

# collect all C57BL6/J mice data
all.c57bl6.json.group1 <- fromJSON(getURL(all.c57bl6.url.group1))
all.c57bl6.json.group2 <- fromJSON(getURL(all.c57bl6.url.group2))
all.c57bl6.json.group3 <- fromJSON(getURL(all.c57bl6.url.group3))
all.c57bl6.json.group4 <- fromJSON(getURL(all.c57bl6.url.group4))
all.c57bl6.json.group5 <- fromJSON(getURL(all.c57bl6.url.group5))
all.c57bl6.json.group6 <- fromJSON(getURL(all.c57bl6.url.group6))
all.c57bl6.json.group7 <- fromJSON(getURL(all.c57bl6.url.group7))
library(plyr)

df.1 <- ldply(lapply(all.c57bl6.json.group1[[2]],function(x) do.call(c,unlist(x,r=F))),as.data.frame)
df.2 <- ldply(lapply(all.c57bl6.json.group2[[2]],function(x) do.call(c,unlist(x,r=F))),as.data.frame)
df.3 <- ldply(lapply(all.c57bl6.json.group3[[2]],function(x) do.call(c,unlist(x,r=F))),as.data.frame)
df.4 <- ldply(lapply(all.c57bl6.json.group4[[2]],function(x) do.call(c,unlist(x,r=F))),as.data.frame)
df.5 <- ldply(lapply(all.c57bl6.json.group5[[2]],function(x) do.call(c,unlist(x,r=F))),as.data.frame)
df.6 <- ldply(lapply(all.c57bl6.json.group6[[2]],function(x) do.call(c,unlist(x,r=F))),as.data.frame)
df.7 <- ldply(lapply(all.c57bl6.json.group7[[2]],function(x) do.call(c,unlist(x,r=F))),as.data.frame)
 
#create mock columns for jagged data frames
for (column in colnames(df.6)[ is.na(match(colnames(df.6), colnames(df.7)))]){
  df.7[,column] <- rep(NA, dim(df.7)[1])
}

#all combined
all.c57bl6 <- rbind(df.1,df.2,df.3,df.4,df.5,df.6,df.7)


all.c57bl6$animal.MouseID  <- as.factor(all.c57bl6$animal.MouseID )
#assays of interest
assays.tested <- c('Body Weight', 'Lean Mass', 'Total Fat Mass')
 all.c57bl6 <- subset( all.c57bl6, assay.assay%in%assays.tested)
 
#determine mouse ids for pups treatment group
 pups.treatment.url <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/treatment/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=0&treatment=Pups%20Treatment'
 pups.treatment.json <- fromJSON(getURL(pups.treatment.url))
 pups.treatment.mouseids <- as.factor(unlist(pups.treatment.json[[2]][[1]]['animals'])[names(unlist(pups.treatment.json[[2]][[1]]['animals'])) == 'animals.id'])

#determine mouse ids for pups treatment group
pups.untagged.url <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/treatment/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=0&treatment=Pup%20Untagged'
pups.untagged.json <- fromJSON(getURL(pups.untagged.url))
pups.untagged.mouseids <- as.factor(unlist(pups.untagged.json[[2]][[1]]['animals'])[names(unlist(pups.untagged.json[[2]][[1]]['animals'])) == 'animals.id'])

#determine mouse ids for maternally control pups
maternal.control.url <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/treatment/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=0&treatment=Maternal%20Particulate%20-%20Saline'
maternal.control.json <- fromJSON(getURL(maternal.control.url))
maternal.control.mouseids <- as.factor(unlist(maternal.control.json[[2]][[1]]['animals'])[names(unlist(maternal.control.json[[2]][[1]]['animals'])) == 'animals.id'])

#determine mouse ids for maternally treated pups
maternal.particulate.url <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/treatment/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=0&treatment=Maternal%20Particulate%20Inhalation'
maternal.particulate.json <- fromJSON(getURL(maternal.particulate.url))
maternal.particulate.mouseids <- as.factor(unlist(maternal.particulate.json[[2]][[1]]['animals'])[names(unlist(maternal.particulate.json[[2]][[1]]['animals'])) == 'animals.id'])

#determine mouse ids for maternally treated pups with cabosil
maternal.cabosil.url <- 'http://bridgeslab.uthsc.edu/mousedb/api/v1/treatment/?format=json&username=davebridges&api_key=fce3fde2a9a2e5dc9e04c20aad90120a621c50b3&limit=0&treatment=Maternal%20Particulate-%20Cabosil'
maternal.cabosil.json <- fromJSON(getURL(maternal.cabosil.url))
maternal.cabosil.mouseids <- as.factor(unlist(maternal.cabosil.json[[2]][[1]]['animals'])[names(unlist(maternal.cabosil.json[[2]][[1]]['animals'])) == 'animals.id'])
 
data.treatment <- droplevels(all.c57bl6[all.c57bl6$animal.id  %in% pups.treatment.mouseids,])
data.untagged <- droplevels(all.c57bl6[all.c57bl6$animal.id  %in% pups.untagged.mouseids,])
# 
#set the treatment column
data.treatment$Treatment <- as.factor(rep("MCP230", dim(data.treatment)[1]))
data.untagged$Treatment <- as.factor(rep("Saline", dim(data.untagged)[1]))
# 
data.pups <- rbind(data.treatment, data.untagged)
data.pups$Weight <- as.numeric(as.character(data.pups$values))/1000
#calculated the week based on teh age of the measurement
data.pups$Week <- as.integer(round((data.pups$age - 70)/7,0))


data.maternal.control <- droplevels(all.c57bl6[all.c57bl6$animal.id  %in% maternal.control.mouseids,])
data.maternal.particulate <- droplevels(all.c57bl6[all.c57bl6$animal.id  %in% maternal.particulate.mouseids,])
data.maternal.cabosil <- droplevels(all.c57bl6[all.c57bl6$animal.id  %in% maternal.cabosil.mouseids,])
# 
#set the treatment column
data.maternal.control$Treatment <- as.factor(rep("Saline", dim(data.maternal.control)[1]))
data.maternal.particulate$Treatment <- as.factor(rep("MCP230", dim(data.maternal.particulate)[1]))
data.maternal.cabosil$Treatment <- as.factor(rep("Cabosil", dim(data.maternal.cabosil)[1]))
# 
data.maternal <- rbind(data.maternal.control, data.maternal.particulate, data.maternal.cabosil)
data.maternal$Weight <- as.numeric(as.character(data.maternal$values))/1000
#calculated the week based on the age of the measurement
#what age were the mice at the start
data.maternal$Start.Age <- rep(NA, dim(data.maternal)[1])
for (mouse in levels(data.maternal$animal.MouseID)) {
  if (data.maternal[data.maternal$animal.MouseID==mouse,'Treatment'] == "Particulate") {
    data.maternal[data.maternal$animal.MouseID==mouse,]$Start.Age <- rep(data.maternal[data.maternal$animal.MouseID==mouse&data.maternal$experiment.date%in%c('2014-04-09','2014-09-24'),]$age, dim(data.maternal[data.maternal$animal.MouseID==mouse,])[1])
  }
  else 
    data.maternal[data.maternal$animal.MouseID==mouse,]$Start.Age <- rep(data.maternal[data.maternal$animal.MouseID==mouse&data.maternal$experiment.date%in%c('2014-04-16','2014-09-24'),]$age, dim(data.maternal[data.maternal$animal.MouseID==mouse,])[1])
}

data.maternal$Week <- as.integer(round((data.maternal$age - data.maternal$Start.Age)/7,0))
write.csv(data.pups,output_file_pups)
write.csv(data.maternal,output_file_maternal)
}

#uncomment this to update
#update.data()

data.pups <- subset(read.csv(output_file_pups, row.names="X"), assay.assay=="Body Weight"&animal.id>6300)
#removed older outlier pups
data.pups <- data.pups[!(data.pups$animal.MouseID %in% c(773,765,767, 324)),]
data.pups$animal.MouseID <- as.factor(data.pups$animal.MouseID)
data.pups$animal.Cage <- as.factor(data.pups$animal.Cage)
data.pups$Treatment <- relevel(data.pups$Treatment, ref='Saline')
max.week.pups <- 9

data.maternal <- subset(read.csv(output_file_maternal, row.names="X"), assay.assay=="Body Weight")
#removed sickly, weight losing mouse 206
data.maternal <- subset(data.maternal, animal.MouseID !=206)
data.maternal <- subset(data.maternal, experiment.feeding_state == 'fed')
data.maternal$animal.MouseID <- as.factor(data.maternal$animal.MouseID)
data.maternal$animal.Cage <- as.factor(data.maternal$animal.Cage)
data.maternal$Treatment <- relevel(data.maternal$Treatment, ref='Saline')
for (row in rownames(data.maternal)) {
  if (data.maternal[row,'animal.id'] < 6400)
    data.maternal[row,'Cohort'] <- "First Cohort"
  else
    data.maternal[row,'Cohort'] <- "Second Cohort"
}
data.maternal$Cohort <- as.factor(data.maternal$Cohort)
@

\section*{Animals Treated with Particulate Matter as Pups}

<<statistics-pups, echo=FALSE>>=
library(lme4)
fit.lme.pups <- lmer(Weight~age+Treatment + (1|animal.MouseID), data=data.pups[data.pups$age >= 70,], REML=T)
fit.lme.interaction.pups <- lmer(Weight~ age * Treatment + (1|animal.MouseID), data=data.pups[data.pups$age >= 70,], REML=T)
fit.lme.no.treatment.pups <- lmer(Weight~ age + (1|animal.MouseID), data=data.pups[data.pups$age >= 70,], REML=T)

library(multcomp)
#for post-hoc testing of the mixed effects model, if it was significant
#summary(glht(fit.lme, linfct=mcp(Genotype="Dunnett")))

#p-values at each week
weekly.pairwise.tests.pups <- data.frame(row.names=as.factor(seq(0,12,1)))
for (week in seq(0,max.week.pups,1)){
  weekly.pairwise.tests.pups[as.character(week),'shapiro-untagged'] <- with(data.pups[data.pups$Week==week&data.pups$Treatment=='Saline',], shapiro.test(Weight))$p.value
  weekly.pairwise.tests.pups[as.character(week),'shapiro-treatment'] <- with(data.pups[data.pups$Week==week&data.pups$Treatment=='MCP230',], shapiro.test(Weight))$p.value
  #weekly.pairwise.tests.pups[week,'levene'] <- leveneTest(Weight~Treatment, data=data.pups[data.pups$Week==week,])$`Pr(>F)`[1]
  weekly.pairwise.tests.pups[as.character(week),'wilcoxon'] <- wilcox.test(Weight~Treatment, data=data.pups[data.pups$Week==week,], var.equal=T)$p.value
    weekly.pairwise.tests.pups[as.character(week),'shapiro-untagged'] <- with(data.pups[data.pups$Week==week&data.pups$Treatment=='Saline',], shapiro.test(Weight))$p.value
  weekly.pairwise.tests.pups[as.character(week),'shapiro-treatment'] <- with(data.pups[data.pups$Week==week&data.pups$Treatment=='MCP230',], shapiro.test(Weight))$p.value
  #weekly.pairwise.tests.pups[week,'levene'] <- leveneTest(Weight~Treatment, data=data.pups[data.pups$Week==week,])$`Pr(>F)`[1]
  weekly.pairwise.tests.pups[as.character(week),'n'] <- dim(data.pups[data.pups$Week==week,])[1]
}
weekly.pairwise.tests.pups$padj <- p.adjust(weekly.pairwise.tests.pups$wilcoxon, method="BH")

#calculate weekly averages
library(plyr)
weekly.summary.pups <- ddply(subset(data.pups, Week >= 0&Week<=12), .(Treatment,Week), summarize,
     mean = mean(Weight),
     se = sd(Weight, na.rm=T)/sqrt(length(Weight)),
     sd = sd(Weight, na.rm=T),
     n = length(Weight))
@

This study includes \Sexpr{length(levels(data.pups$animal.MouseID))} animals, all put on a high fat diet.  This includes \Sexpr{length(levels(droplevels(data.pups[data.pups$Treatment=="Treatment"&data.pups$Week==max.week.pups,])$animal.MouseID))} animals in the treatment group and \Sexpr{length(levels(droplevels(data.pups[data.pups$Treatment=="Untagged"&data.pups$Week==max.week.pups,]$animal.MouseID)))} animals in the untagged group.  Currently we are blind to the identity of these groups.  The raw data is written into \Sexpr{output_file_pups} in this folder.

The weights of each mouse are shown in Figure \ref{fig:scatterplot-weekly-pups}.  By mixed linear effects modelling of body weights after the start of the diet, there was no significant effect of the Treatment (p = \Sexpr{round(anova(fit.lme.pups,fit.lme.no.treatment.pups, test="F")$`Pr(>Chisq)`[2],3)}) by F-test.  There was no evidence of an interaction between the age covariate and the treatment  (p = \Sexpr{round(anova(fit.lme.pups,fit.lme.interaction.pups, test="F")$`Pr(>Chisq)`[2],3)}).

Presuming linear body weight gain on the diet, the \Sexpr{names(fixef(fit.lme.pups))[3]} group weighs \Sexpr{round(fixef(fit.lme.pups)[3],2)} $\pm$ \Sexpr{round(sqrt(diag(vcov(fit.lme.pups)))[3],2)}g more (mean $\pm$ SEM).  We also did pairwise testing at each week.  First we tested for normality with Shapiro-Wilk tests on each group and then, because in general all weeks in the untagged group tended to have a non-normal distribution, we did Wilcoxon rank-sum tests.  These are shown in Table \ref{tab:pairwise-tests-pups}.


\begin{figure}
\begin{center}
<<label=scatterplot-weekly-pups,fig=TRUE,echo=FALSE>>=
library(reshape2)
summary.data.pups <- dcast(weekly.summary.pups, Week~Treatment, value.var="mean")
summary.error.pups <- dcast(weekly.summary.pups, Week~Treatment, value.var="se")
ymax <- max(summary.data.pups + summary.error.pups, na.rm=T)
plot <- plot(summary.data.pups$Week, summary.data.pups$Saline,
                   pch=19, las=1, cex=0.5,
                   ylab ="Body Weight (g)",
                   xlab ="Weeks on Diet",
                   ylim = c(25,ymax))
lines(summary.data.pups$Week, summary.data.pups$Saline, col=palette()[1])
points(summary.data.pups$Week, summary.data.pups$MCP230, pch=19, cex=0.5, col=palette()[2])
lines(summary.data.pups$Week, summary.data.pups$MCP230, col=palette()[2])

legend("topleft", levels(data.pups$Treatment), bty="n", pch=19, col=palette()[1:2], lty=1)

superpose.eb <- function (x, y, ebl, ebu = ebl, length = 0.08, ...)
  arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3,
  length = length, ...)

superpose.eb(summary.data.pups$Week, summary.data.pups$Saline, summary.error.pups$Saline, col=palette()[1])
superpose.eb(summary.data.pups$Week, summary.data.pups$MCP230, summary.error.pups$MCP230, col=palette()[2])
@
\end{center}
\caption{Weights of Pups with Inhaled Particulate Matter by Week.}
\label{fig:scatterplot-weekly-pups}
\end{figure}

\begin{figure}
\begin{center}
<<label=scatterplot-weekly-max-pups,fig=TRUE,echo=FALSE>>=
library(reshape2)
summary.data.pups <- dcast(subset(weekly.summary.pups, Week<=max.week.pups-1), Week~Treatment, value.var="mean")
summary.error.pups <- dcast(subset(weekly.summary.pups, Week<=max.week.pups-1), Week~Treatment, value.var="se")
ymax <- max(data.pups$Weight)
with(data.pups, plot(age, Weight,
                   pch=19, las=1, cex=0.5,
                   ylab ="Body Weight (g)",
                   xlab ="Age (days)",
                   ylim=c(min(Weight, na.rm=T),max(Weight, na.rm=T)),
                   xlim=c(min(age, na.rm=T),max(age, na.rm=T)),
                   col=Treatment))
legend("topleft", levels(data.pups$Treatment), bty="n", pch=19, col=palette()[1:2], lty=1)
data.pups.ordered <- data.pups[order(data.pups$age),]
with(data.pups.ordered[data.pups.ordered$Treatment == levels(data.pups.ordered$Treatment)[2],], lines(age, predict(loess(Weight~age, span=0.9)), col=palette()[2]))
with(data.pups.ordered[data.pups.ordered$Treatment == levels(data.pups.ordered$Treatment)[1],], lines(age, predict(loess(Weight~age, span=0.9)), col=palette()[1]))
legend("topleft", levels(data.pups$Treatment), bty="n", pch=19, col=palette()[1:2], lty=1)
@
\end{center}
\caption{Weights of Pups with Inhaled Particulate Matter by Week}
\label{fig:scatterplot-weekly-max-pups}
\end{figure}


<<label=summary-tables-pups,echo=FALSE,results=tex>>=
library(xtable)
print(xtable(weekly.pairwise.tests.pups, label="tab:pairwise-tests-pups", caption="Shapiro-Wilk and Wilcoxon Tests per week", digits=3))
@

\section*{Animals Reared from Particulate Treated Mothers}

<<statistics-maternal, echo=FALSE>>=
#calculate weekly averages by Cage
weekly.summary.maternal.cage <- ddply(subset(data.maternal, Week >= 0), .(animal.Cage, Treatment,Week), summarize,
     mean = mean(Weight),
     se = sd(Weight, na.rm=T)/sqrt(length(Weight)),
     sd = sd(Weight, na.rm=T),
     n = length(Weight))

max.week.maternal <- 11
library(lme4)
fit.lme.maternal <- lmer(mean~Week + Treatment + (1|animal.Cage), data=weekly.summary.maternal.cage, REML=T)
fit.lme.no.treatment.maternal <- lmer(mean~ Week + (1|animal.Cage), data=weekly.summary.maternal.cage, REML=T)

fit.lme.maternal.indiv <- lmer(Weight~Week + Treatment + (1|animal.MouseID), data=subset(data.maternal, Week >= 0), REML=T)
fit.lme.no.treatment.maternal.indiv <- lmer(Weight~ Week + (1|animal.MouseID), data=subset(data.maternal, Week >= 0), REML=T)
library(multcomp)
#for post-hoc testing of the mixed effects model, if it was significant
#summary(glht(fit.lme, linfct=mcp(Genotype="Dunnett")))

#p-values at each week
library(car)
#weekly.pairwise.tests.maternal <- data.frame(row.names=as.factor(seq(0,max.week.maternal,1)))
#for (week in seq(0,max.week.maternal,1)){
#  weekly.pairwise.tests.maternal[as.character(week),'shapiro-saline'] <- with(weekly.summary.maternal.cage[weekly.summary.maternal.cage$Week==week&weekly.summary.maternal.cage$Treatment=='Saline',], shapiro.test(mean))$p.value
#  weekly.pairwise.tests.maternal[as.character(week),'shapiro-particulate'] <- with(weekly.summary.maternal.cage[weekly.summary.maternal.cage$Week==week&weekly.summary.maternal.cage$Treatment=='MCP230',], shapiro.test(mean))$p.value
 # weekly.pairwise.tests.maternal[as.character(week),'levene'] <- leveneTest(mean~Treatment, data=weekly.summary.maternal.cage[weekly.summary.maternal.cage$Week==week,])$`Pr(>F)`[1]
#  weekly.pairwise.tests.maternal[as.character(week),'student'] <- t.test(mean~Treatment, data=weekly.summary.maternal.cage[weekly.summary.maternal.cage$Week==week,], var.equal=T)$p.value
#    weekly.pairwise.tests.maternal[as.character(week),'n'] <- dim(weekly.summary.maternal.cage[weekly.summary.maternal.cage$Week==week,])[1]
#}
#weekly.pairwise.tests.maternal$padj <- p.adjust(weekly.pairwise.tests.maternal$student, method="BH")

#calculate weekly averages
weekly.summary.maternal <- ddply(subset(data.maternal, Week >= 0), .(Treatment,Week), summarize,
     mean = mean(Weight),
     se = sd(Weight, na.rm=T)/sqrt(length(Weight)),
     sd = sd(Weight, na.rm=T),
     n = length(Weight))
@

This study includes \Sexpr{length(levels(data.maternal$animal.MouseID))} animals, all put on a high fat diet.  This includes \Sexpr{length(data.maternal[data.maternal$Treatment=="Control"&data.maternal$Week==max.week.maternal,]$animal.MouseID)} animals in the control group and \Sexpr{length(data.maternal[data.maternal$Treatment=="Particulate"&data.maternal$Week==max.week.maternal,]$animal.MouseID)} animals in the particulate group.  The raw data is written into \Sexpr{output_file_pups} in this folder.

The weights of each mouse are shown in Figure \ref{fig:scatterplot-maternal}. We aggregated the data by cage, which means we grouped mice together by the mother. By mixed linear effects modelling of body weights after the start of the diet, there was no significant effect of the Treatment (p = \Sexpr{round(anova(fit.lme.maternal,fit.lme.no.treatment.maternal, test="F")$`Pr(>Chisq)`[2],3)}) by F-test.   If we treat each mouse individually then the p-value is \Sexpr{round(anova(fit.lme.maternal.indiv,fit.lme.no.treatment.maternal.indiv, test="F")$`Pr(>Chisq)`[2],3)}.

First we tested for normality with Shapiro-Wilk tests on each group and then, because in general all weeks in the untagged group tended to have a normal distributions with equal variance, we did Student's T-Tests.  These are shown in Table \ref{tab:pairwise-tests-maternal}.


\begin{figure}
\begin{center}
<<label=scatterplot-maternal,fig=TRUE,echo=FALSE>>=
with(data.maternal, plot(age, Weight,
                   pch=19, las=1, cex=0.5,
                   ylab ="Body Weight (g)",
                   xlab ="Age (days)",
                   ylim=c(min(Weight, na.rm=T),max(Weight, na.rm=T)),
                   xlim=c(min(age, na.rm=T),max(age, na.rm=T)),
                   col=Treatment))
legend("topleft", levels(data.maternal$Treatment), bty="n", pch=19, col=palette()[1:3], lty=1)

data.maternal.ordered <- data.maternal[order(data.maternal$age),]
#add smoothened lines
with(data.maternal.ordered[data.maternal.ordered$Treatment == levels(data.maternal.ordered$Treatment)[1],], lines(age, predict(loess(Weight~age, span=0.9)), col=palette()[1]))
with(data.maternal.ordered[data.maternal.ordered$Treatment == levels(data.maternal$Treatment)[2],], lines(age, predict(loess(Weight~age, span=0.9)), col=palette()[2]))
with(data.maternal.ordered[data.maternal.ordered$Treatment == levels(data.maternal$Treatment)[3],], lines(age, predict(loess(Weight~age, span=0.9)), col=palette()[3]))
arrows(70,33,70,30, length=0.1)
text(70,35,"Start HFD")
@
\end{center}
\caption{Weights of Pups Who's Mothers were Treated with Inhaled Particulate Matter by Week. Note each mouse may be shown multiple times.}
\label{fig:scatterplot-maternal}
\end{figure}

\begin{figure}
\begin{center}
<<label=scatterplot-maternal-cage,fig=TRUE,echo=FALSE>>=
summary.data.maternal <- dcast(weekly.summary.maternal.cage, Week~Treatment, value.var="mean", mean)
se <- function(x) sd(x)/sqrt(length(x))
summary.error.maternal <- dcast(weekly.summary.maternal.cage, Week~Treatment, value.var="mean", se)
ymax <- max(weekly.summary.maternal.cage$mean + weekly.summary.maternal.cage$se, na.rm=T)
plot <- with(weekly.summary.maternal.cage, plot(Week, mean,
                   pch=19, las=1, cex=0.5,
                   ylab ="Body Weight (g)",
                   xlab ="Weeks on Diet",
                   col=Treatment,
                   ylim = c(25,ymax)))
lines(summary.data.maternal$Week, summary.data.maternal$Control, col=palette()[1])
lines(summary.data.maternal$Week, summary.data.maternal$Particulate, col=palette()[2])

legend("topleft", levels(data.maternal$Treatment), bty="n", pch=19, col=palette()[1:2], lty=1)

with(weekly.summary.maternal.cage[weekly.summary.maternal.cage$Treatment=='Control',],
     superpose.eb(Week, mean, se, col=palette()[1]))
with(weekly.summary.maternal.cage[weekly.summary.maternal.cage$Treatment=='Particulate',],
     superpose.eb(Week, mean, se, col=palette()[2]))
@
\end{center}
\caption{Weights of Pups Who's Mothers were Treated with Inhaled Particulate Matter by Week.  Each dot represents a single mother (cage). Note each cage may be shown multiple times.}
\label{fig:scatterplot-maternal-cage}
\end{figure}

\begin{figure}
\begin{center}
<<label=scatterplot-weekly-maternal,fig=TRUE,echo=FALSE>>=
summary.data.maternal <- dcast(weekly.summary.maternal, Week~Treatment, value.var="mean")
summary.error.maternal <- dcast(weekly.summary.maternal, Week~Treatment, value.var="se")
ymax <- max(summary.data.maternal + summary.error.maternal, na.rm=T)
plot <- plot(summary.data.maternal$Week, summary.data.maternal$Saline,
                   pch=19, las=1, cex=0.5,
                   ylab ="Body Weight (g)",
                   xlab ="Weeks on Diet",
                   ylim = c(25,ymax))
lines(summary.data.maternal$Week, summary.data.maternal$Saline, col=palette()[1])
lines(summary.data.maternal$Week, summary.data.maternal$MCP230, col=palette()[2])
points(summary.data.maternal$Week, summary.data.maternal$MCP230,pch=19, col=palette()[2], cex=0.5)
legend("topleft", levels(data.maternal$Treatment), bty="n", pch=19, col=palette()[1:2], lty=1)

superpose.eb(summary.data.maternal$Week, summary.data.maternal$Saline, summary.error.maternal$Saline, col=palette()[1])
superpose.eb(summary.data.maternal$Week, summary.data.maternal$MCP230, summary.error.maternal$MCP230, col=palette()[2])
@
\end{center}
\caption{Weights of Pups Who's Mothers were Treated with Inhaled Particulate Matter by Week.}
\label{fig:scatterplot-weekly-maternal}
\end{figure}

\begin{figure}
\begin{center}
<<label=scatterplot-weekly-maternal-cohort,fig=TRUE,echo=FALSE>>=
par(mfrow=c(1,2))
weekly.summary.maternal.cohort <- ddply(subset(data.maternal, Week >= 0), .(Cohort,Treatment,Week), summarize,
     mean = mean(Weight),
     se = sd(Weight, na.rm=T)/sqrt(length(Weight)),
     sd = sd(Weight, na.rm=T),
     n = length(Weight))

ymax <- max(summary.data.maternal + summary.error.maternal, na.rm=T)
summary.data.maternal <- dcast(subset(weekly.summary.maternal.cohort, Cohort=="First Cohort"), Week~Treatment, value.var="mean")
summary.error.maternal <- dcast(subset(weekly.summary.maternal.cohort, Cohort=="First Cohort"), Week~Treatment, value.var="se")
plot <- plot(summary.data.maternal$Week, summary.data.maternal$Saline,
                   pch=19, las=1, cex=0.5,
                   ylab ="Body Weight (g)",
                   xlab ="Weeks on Diet",
                   ylim = c(23,ymax))
lines(summary.data.maternal$Week, summary.data.maternal$Saline, col=palette()[1])
lines(summary.data.maternal$Week, summary.data.maternal$Cabosil, col=palette()[2])
points(summary.data.maternal$Week, summary.data.maternal$Cabosil,pch=19, col=palette()[2], cex=0.5)
lines(summary.data.maternal$Week, summary.data.maternal$MCP230, col=palette()[3])
points(summary.data.maternal$Week, summary.data.maternal$MCP230,pch=19, col=palette()[3], cex=0.5)
legend("topleft", levels(data.maternal$Treatment)[c(1,3)], bty="n", pch=19, col=palette()[c(1,3)], lty=1)

superpose.eb(summary.data.maternal$Week, summary.data.maternal$Saline, summary.error.maternal$Saline, col=palette()[1])
superpose.eb(summary.data.maternal$Week, summary.data.maternal$MCP230, summary.error.maternal$MCP230, col=palette()[3])

#second cohort
summary.data.maternal <- dcast(subset(weekly.summary.maternal.cohort, Cohort=="Second Cohort"), Week~Treatment, value.var="mean")
summary.error.maternal <- dcast(subset(weekly.summary.maternal.cohort, Cohort=="Second Cohort"), Week~Treatment, value.var="se")
plot <- plot(summary.data.maternal$Week, summary.data.maternal$Saline,
                   pch=19, las=1, cex=0.5,
                   ylab ="Body Weight (g)",
                   xlab ="Weeks on Diet",
                   ylim = c(23,ymax),
                   xlim = c(0,12))
lines(summary.data.maternal$Week, summary.data.maternal$Saline, col=palette()[1])
lines(summary.data.maternal$Week, summary.data.maternal$Cabosil, col=palette()[2])
points(summary.data.maternal$Week, summary.data.maternal$Cabosil,pch=19, col=palette()[2], cex=0.5)
lines(summary.data.maternal$Week, summary.data.maternal$MCP230, col=palette()[3])
points(summary.data.maternal$Week, summary.data.maternal$MCP230,pch=19, col=palette()[3], cex=0.5)
legend("topleft", levels(data.maternal$Treatment), bty="n", pch=19, col=palette()[1:3], lty=1)

superpose.eb(summary.data.maternal$Week, summary.data.maternal$Saline, summary.error.maternal$Saline, col=palette()[1])
superpose.eb(summary.data.maternal$Week, summary.data.maternal$Cabosil, summary.error.maternal$Cabosil, col=palette()[2])
superpose.eb(summary.data.maternal$Week, summary.data.maternal$MCP230, summary.error.maternal$MCP230, col=palette()[3])
@
\end{center}
\caption{Weights of Pups Who's Mothers were Treated with Inhaled Particulate Matter by Week and By Cohort.}
\label{fig:scatterplot-weekly-maternal-cohort}
\end{figure}


<<label=summary-tables-maternal,echo=FALSE,results=tex>>=
library(xtable)
#print(xtable(weekly.pairwise.tests.maternal, label="tab:pairwise-tests-maternal", caption="Shapiro-Wilk and Wilcoxon Tests per week for maternally treated mice", digits=3))
#print(xtable(weekly.summary.maternal, label="tab:weekly-summary-maternal", caption="Summary statistics for maternally treated mice", digits=3))
@


\section*{Session Information}
<<sessionInfo, results=tex, echo=F>>=
toLatex(sessionInfo())
@


\end{document}
