---
title: "Identifying and cleaning the comorbidity data for pneumonia"
author: "Dave Bridges"
date: "February 1, 2024"
output:
  html_document:
    highlight: tango
    keep_md: yes
    number_sections: yes
    toc: yes
---

## Purpose

To analyse the subset of patients with viral or bacterial pneumonia.   This script combines the cleaned datasets and writes out a complete datafile for analyses.  This script can be found in `r getwd()` and was most recently run on `r date()`.

```{r input-data}
library(knitr)
#figures made will go to directory called figures, will make them as both png and pdf files 
opts_chunk$set(fig.path='figures-cm/',
               echo=TRUE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
options(scipen = 2, digits = 3)

library(readr)
library(dplyr)
library(tidyr)
library(knitr)
library(lubridate)

comorbiditites.datafile <- 'Comorbidities_clean.csv'
pneumonia.encounters.datafile <- 'PneumoniaEncounterData.csv'
demographic.datafile <- 'DemographicDataClean.csv'
```

# Combining  files

```{r combining}
cm.data <- read_csv(comorbiditites.datafile)
pneu.data <- read_csv(pneumonia.encounters.datafile)
demographic.data <- read_csv(demographic.datafile)

combined.data <-
  left_join(pneu.data,cm.data,by="DeID_PatientID") %>%
  left_join(demographic.data,by="DeID_PatientID") %>%
  mutate(Diabetes = ifelse(DiabetesWithChronicComplication==1|DiabetesWithoutChronicComplication==1,1,0)) %>%
  mutate(DiabetesFirst = pmin(DiabetesWithoutChronicComplicationFirst,DiabetesWithChronicComplicationFirst,na.rm=T)) %>% #first date between both diabetes
  mutate(Hypertension = ifelse(HypertensionComplicated==1|HypertensionUncomplicated==1,1,0)) %>% 
  mutate(HypertensionFirst = pmin(HypertensionComplicatedFirst,HypertensionUncomplicatedFirst,na.rm=T)) %>%
  mutate(Survival = as.Date(mdy_hm(DeID_DeathIndexDeceasedDate))-ymd(AdmitDate)) %>%
  mutate(Survival.30day = if_else(Survival <= 30 , "Within 30 Days","Surival Past 30 Days")) %>%
  mutate(Survival.60day = if_else(Survival <= 60 , "Within 60 Days","Surival Past 60 Days")) %>%
  mutate(PriorObesity = case_when(Obesity == 1 & ObesityFirst<AdmitDate ~ 1,
                                Obesity == 1 & ObesityFirst>=AdmitDate ~ 0,
                                Obesity==0~0,
                                is.na(Obesity)~0,
                                is.na(ObesityFirst)~0,
                                .default=0
                                )) %>% 
    mutate(PriorCOPD = case_when(COPD == 1 & COPDFirst<AdmitDate ~ 1,
                                COPD == 1 & COPDFirst>=AdmitDate ~ 0,
                                COPD==0~0,
                                is.na(COPD)~0,
                                is.na(COPDFirst)~0,
                                .default=0
                                )) %>%
  mutate(PriorDiabetes = case_when(Diabetes == 1 & DiabetesFirst<AdmitDate ~ 1,
                                Diabetes == 1 & DiabetesFirst>=AdmitDate ~ 0,
                                Diabetes==0~0,
                                is.na(Diabetes)~0,
                                is.na(DiabetesFirst)~0,
                                .default=0
                                )) %>%
  mutate(PriorHypertension = case_when(Hypertension == 1 & HypertensionFirst<AdmitDate ~ 1,
                                Hypertension == 1 & HypertensionFirst>=AdmitDate ~ 0,
                                Hypertension==0~0,
                                is.na(Hypertension)~0,
                                is.na(HypertensionFirst)~0,
                                .default=0
                                )) %>%
  mutate(PriorCardiacArrhythmias = case_when(CardiacArrhythmias == 1 & HypertensionFirst<AdmitDate ~ 1,
                                CardiacArrhythmias == 1 & CardiacArrhythmiasFirst>=AdmitDate ~ 0,
                                CardiacArrhythmias==0~0,
                                is.na(CardiacArrhythmias)~0,
                                is.na(HypertensionFirst)~0,
                                .default=0
                                )) 

complete.filename <- 'DatasetComplete.csv'
write_csv(combined.data, complete.filename)
```


Wrote this out to `r complete.filename`.

# Session Information

```{r sessioninfo}
sessionInfo()
```
